### ISSUE TITLE
[BUG?] 

### ISSUE THREAD

**Issue by kfitzpatrick** [knrz/iterm-workspace#2]
When I install and then run `bootstrap-iterm-workspace` I'm see the following error:

> /usr/local/bin/bootstrap-iterm-workspace: execution error: Error: TypeError: undefined is not an object (evaluating 'tabs.map') (-2700)

Is this a known issue?

**Comment by CyrusNuevoDia** [comment]
Hey man! It's not a known bug — in the [installation steps](https://github.com/knrz/iterm-workspace#getting-started--installation) I never expected anyone to call `bootstrap-iterm-workspace` directly. If you call `start-iterm-workspace` it should set you up with a sample config and then you can run `start-iterm-workspace` again to run the config.

**Comment by CyrusNuevoDia** [comment]
Looking at the source for `bootstrap-iterm-workspace` it expects the config file as the first (undocumented) argument, so if you want to have a custom config file path (other than the default `.iterm-workspace`) then you can run it like `bootstrap-iterm-workspace path/to/my/config`. Without the path to the config you run into that TypeError.

**Comment by kfitzpatrick** [comment]
Gotcha, thanks!
